version: '3.1'
services:  
  postgres:    
    image: postgres:11   
    environment:      
      - POSTGRES_USER=admin     
      - POSTGRES_PASSWORD=nopandea
      - POSTGRES_DB=stg   
    volumes:      
      - ./postgres-data/postgres:/var/lib/postgresql/data   
    ports:      
      - "5786:5432"  
  app:  
    restart: always  
    build: .  
    ports:    
      - 5000:5000  
    volumes:     
      - .:/app 
    depends_on:    
      - postgres
    entrypoint: ["python", "index.py"]  
    